server:
  port: 8001
spring:
    datasource:
        name: datasource
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/springcloud
        username: root
        password: root
    application:
      name: user-server

mybatis:
    type-aliases-package: com.demo.model
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
    mapper-locations: classpath:com/demo/dao/*.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8002/eureka/
  instance:
    instance-id: user-server
    prefer-ip-address: true
logging:
    path: E:/springbootLog
    file: test.log